name: tccon-qc
channels:
  - conda-forge
dependencies:
  - matplotlib=3.3
  - matplotlib-base=3.3
  - netcdf4=1.6
  - numpy=1.21
  - pandas=1.3
  - pillow=8
  - pip=21
  - pypdf2=2
  - python=3.9
  - scipy=1.6
  - pip:
    - tomli==1.0.4
