name: tccon-qc
channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib=3.3.2
  - matplotlib-base=3.3.2
  - netcdf4=1.5.4
  - numpy
  - pandas
  - pillow
  - pip=21
  - pypdf2
  - python=3.7
  - scipy=1.6.1
  - pip:
    - tomli==1.0.4
