[site_data.ae.mod_data.level0]
Height = 0.069

[site_data.an.mod_data.level0]
Height = 0.093

[site_data.bi.mod_data.level0]
Height = 0.199

[site_data.br.mod_data.level0]
Height = 0.088

[site_data.bu.mod_data.level0]
Height = 0.174

[site_data.ci.mod_data.level0]
Height = 0.475

[site_data.db.mod_data.level0]
Height = 0.079

[site_data.df.mod_data.level0]
Height = 0.949

[site_data.et.mod_data.level0]
Height = 0.578

[site_data.eu.mod_data.level0]
Height = 0.241

[site_data.fc.mod_data.level0]
Height = 1.921

[site_data.gm.mod_data.level0]
Height = 1.309

# An incorrect abbreviation for Hefei - ginput has "he" in it incorrectly
[site_data.he.mod_data.level0]
Height = 0.091

# The correct abbreviation for Hefei - ginput has "he" in it incorrectly
[site_data.hf.mod_data.level0]
Height = 0.091

[site_data.hw.mod_data.level0]
Height = 0.174

[site_data.if.mod_data.level0]
Height = 0.333

[site_data.iz.mod_data.level0]
Height = 0.213

[site_data.jc.mod_data.level0]
Height = 0.61

[site_data.jf.mod_data.level0]
Height = 0.605

[site_data.js.mod_data.level0]
Height = 0.21

[site_data.jx.mod_data.level0]
Height = 0.608

[site_data.ka.mod_data.level0]
Height = 0.327

[site_data.lh.mod_data.level0]
Height = 0.815

[site_data.ll.mod_data.level0]
Height = 0.817

[site_data.lr.mod_data.level0]
Height = 0.814

[site_data.ma.mod_data.level0]
Height = 0.103

[site_data.ni.mod_data.level0]
Height = 0.22

[site_data.ny.mod_data.level0]
Height = 0.322

[site_data.oc.mod_data.level0]
Height = 0.397

[site_data.or.mod_data.level0]
Height = 0.19

[site_data.pa.mod_data.level0]
Height = 0.537

[site_data.pr.mod_data.level0]
Height = 0.165

[site_data.ra.mod_data.level0]
Height = 0.398

[site_data.rj.mod_data.level0]
Height = 0.477

[site_data.so.mod_data.level0]
Height = 0.283

[site_data.tk.mod_data.level0]
Height = 0.102

[site_data.we.mod_data.level0]
Height = 0.37

[site_data.wg.mod_data.level0]
Height = 0.073

[site_data.xh.mod_data.level0]
Height = 0.096

[site_data.yk.mod_data.level0]
Height = 0.4

[site_data.zs.mod_data.level0]
Height = 1.39
