[mod_data.level0.ae]
Height = 0.069

[mod_data.level0.an]
Height = 0.093

[mod_data.level0.bi]
Height = 0.199

[mod_data.level0.br]
Height = 0.088

[mod_data.level0.bu]
Height = 0.174

[mod_data.level0.ci]
Height = 0.475

[mod_data.level0.db]
Height = 0.079

[mod_data.level0.df]
Height = 0.949

[mod_data.level0.et]
Height = 0.578

[mod_data.level0.eu]
Height = 0.241

[mod_data.level0.fc]
Height = 1.921

[mod_data.level0.gm]
Height = 1.309

[mod_data.level0.he]
Height = 0.091

[mod_data.level0.hw]
Height = 0.174

[mod_data.level0.if]
Height = 0.333

[mod_data.level0.iz]
Height = 0.213

[mod_data.level0.jc]
Height = 0.61

[mod_data.level0.jf]
Height = 0.605

[mod_data.level0.js]
Height = 0.21

[mod_data.level0.jx]
Height = 0.608

[mod_data.level0.ka]
Height = 0.327

[mod_data.level0.lh]
Height = 0.815

[mod_data.level0.ll]
Height = 0.817

[mod_data.level0.lr]
Height = 0.814

[mod_data.level0.ma]
Height = 0.103

[mod_data.level0.ni]
Height = 0.22

[mod_data.level0.ny]
Height = 0.322

[mod_data.level0.oc]
Height = 0.397

[mod_data.level0.or]
Height = 0.19

[mod_data.level0.pa]
Height = 0.537

[mod_data.level0.pr]
Height = 0.165

[mod_data.level0.ra]
Height = 0.398

[mod_data.level0.rj]
Height = 0.477

[mod_data.level0.so]
Height = 0.283

[mod_data.level0.tk]
Height = 0.102

[mod_data.level0.we]
Height = 0.37

[mod_data.level0.wg]
Height = 0.073

[mod_data.level0.xh]
Height = 0.096

[mod_data.level0.yk]
Height = 0.4

[mod_data.level0.zs]
Height = 1.39
