# --------------- #
# Plotting styles #
# --------------- #
[style.default.scatter]
all = {color = "black", marker = "o", markersize = 1}
flag0 = {color = "black", marker = "o", markersize = 1}
flagged = {color = "red", marker = "o", markersize = 1}

[style.main.scatter]
all = {color = "royalblue"}
flag0 = {color = "royalblue"}
flagged = {color = "red"}

[style.ref.scatter]
all = {color = "lightgray"}
flag0 = {color = "lightgray"}

[style.context.scatter]
all = {color = "royalblue"}
flag0 = {color = "royalblue"}
flagged = {color = "tomato"}


[style.default.timeseries]
clone = 'scatter'

[style.main.timeseries]
clone = 'scatter'

[style.ref.timeseries]
clone = 'scatter'

[style.context.timeseries]
clone = 'scatter'


[style.default.timeseries-2panel]
clone = 'scatter'

[style.main.timeseries-2panel]
clone = 'scatter'

[style.ref.timeseries-2panel]
clone = 'scatter'

[style.context.timeseries-2panel]
clone = 'scatter'

# ------------- #
# List of plots #
# ------------- #

[[plots]]
kind = "rolling-timeseries"
yvar = "xluft"
op = "median"

[[plots]]
kind = "timeseries-2panel"
yvar = "xluft"
yerror_var = "xluft_error"

[[plots]]
kind = "timeseries-2panel"
yvar = "xco2"
yerror_var = "xco2_error"

[[plots]]
kind = "timeseries-2panel"
yvar = "xch4"
yerror_var = "xch4_error"

[[plots]]
kind = "timeseries-2panel"
yvar = "xco"
yerror_var = "xco_error"

[[plots]]
kind = "timeseries-2panel"
yvar = "xh2o"
yerror_var = "xh2o_error"

[[plots]]
kind = "timeseries-2panel"
yvar = "xhdo"
yerror_var = "xhdo_error"

[[plots]]
kind = "timeseries-2panel"
yvar = "xhf"
yerror_var = "xhf_error"

[[plots]]
kind = "timeseries-2panel"
yvar = "xn2o"
yerror_var = "xn2o_error"

[[plots]]
kind = "timeseries"
yvar = "vsf_co2"

[[plots]]
kind = "timeseries"
yvar = "vsf_lco2"

[[plots]]
kind = "timeseries"
yvar = "vsf_wco2"

[[plots]]
kind = "timeseries"
yvar = "vsf_hcl"

[[plots]]
kind = "timeseries"
yvar = "vsf_o2"

[[plots]]
kind = "timeseries"
yvar = "vsf_n2o"

[[plots]]
kind = "timeseries"
yvar = "vsf_hf"

[[plots]]
kind = "timeseries"
yvar = "vsf_h2o"

[[plots]]
kind = "timeseries"
yvar = "fvsi"

[[plots]]
kind = "timeseries"
yvar = "lse"

[[plots]]
kind = "timeseries"
yvar = "lsu"

[[plots]]
kind = "timeseries"
yvar = "solzen"

[[plots]]
kind = "timeseries"
yvar = "o2_7885_fs"

[[plots]]
kind = "timeseries"
yvar = "o2_7885_sg"

[[plots]]
kind = "timeseries"
yvar = "zco2_4852a_zo"

[[plots]]
kind = "timeseries"
yvar = "fco2_6154_cfampocl"

[[plots]]
kind = "timeseries"
yvar = "fco2_6154_cfperiod"

[[plots]]
kind = "timeseries"
yvar = "fco2_6154_cfphase"

[[plots]]
kind = "timeseries"
yvar = "dip"

[[plots]]
kind = "timeseries"
yvar = "mvd"

[[plots]]
kind = "timeseries"
yvar = "o2_7885_cl"

[[plots]]
kind = "timeseries"
yvar = "lco2_4852_cl"

[[plots]]
kind = "timeseries"
yvar = "hout"

[[plots]]
kind = "timeseries"
yvar = "tout"

[[plots]]
kind = "timeseries"
yvar = "tmod"

[[plots]]
kind = "delta-timeseries"
yvar1 = "tout"
yvar2 = "tmod"

[[plots]]
kind = "timeseries"
yvar = "h2o_dmf_out"

[[plots]]
kind = "timeseries"
yvar = "h2o_dmf_mod"

[[plots]]
kind = "delta-timeseries"
yvar1 = "h2o_dmf_out"
yvar2 = "h2o_dmf_mod"

[[plots]]
kind = "timeseries"
yvar = "pout"

[[plots]]
kind = "timeseries"
yvar = "pmod"

[[plots]]
kind = "delta-timeseries"
yvar1 = "pout"
yvar2 = "pmod"

[[plots]]
kind = "timeseries"
yvar = "wdir"

[[plots]]
kind = "timeseries"
yvar = "wspd"

[[plots]]
kind = "scatter"
xvar = "solzen"
yvar = "xco2"
resize_to_hexbin = true

[[plots]]
kind = "hexbin"
xvar = "solzen"
yvar = "xco2"

[[plots]]
kind = "scatter"
xvar = "solzen"
yvar = "xluft"
resize_to_hexbin = true

[[plots]]
kind = "hexbin"
xvar = "solzen"
yvar = "xluft"

[[plots]]
kind = "resampled-timeseries"
freq = "D"
op = "median"
yvar = "xluft"

[[plots]]
kind = "resampled-timeseries"
freq = "D"
op = "median"
yvar = "o2_7885_vsf_o2"

[[plots]]
kind = "resampled-timeseries"
freq = "W"
op = "median"
yvar = "xluft"

[[plots]]
kind = "resampled-timeseries"
freq = "W"
op = "median"
yvar = "o2_7885_vsf_o2"

