# --------------- #
# Plotting styles #
# --------------- #
[style.default.scatter]
all = {color = "black", marker = "o", markersize = 1}
flag0 = {color = "black", marker = "o", markersize = 1}
# zorder moves certain points in front/behind others. The default zorder for line series is 2, so setting
# it to < 2 for the flagged data ensures that flagged values are behind the flag0 values.
flagged = {color = "red", marker = "o", markersize = 1, zorder = 1.9}

[style.main.scatter]
all = {color = "royalblue"}
flag0 = {color = "royalblue"}
flagged = {color = "red"}

[style.ref.scatter]
# use zorder to ensure reference data is always in the background
all = {color = "lightgray", zorder=1.7, fit_style = {color = "slategray"}}
flag0 = {color = "lightgray", zorder=1.7, fit_style = {color = "slategray"}}

[style.context.scatter]
# use zorder to keep context behind main data, with flagged data behind the flag0 data
all = {color = "deepskyblue", zorder=1.85, fit_style = {color = "navy"}}
flag0 = {color = "deepskyblue", zorder=1.85, fit_style = {color = "navy"}}
flagged = {color = "gold", zorder=1.8}


[style.main.hexbin]
all = {cmap = "PuBu", bins = "log", mincnt = 1}
flag0 = {cmap = "PuBu", bins = "log", mincnt = 1}

[style.context.hexbin]
all = {cmap = "Greys", bins = "log", mincnt = 1, zorder = 0.8, fit_style = {color = "black"}}
flag0 = {cmap = "Greys", bins = "log", mincnt = 1, zorder = 0.8, fit_style = {color = "black"}}


[style.default.timeseries]
clone = 'scatter'
legend_kws = {ncol = 2}

[style.main.timeseries]
clone = 'scatter'

[style.ref.timeseries]
clone = 'scatter'

[style.context.timeseries]
clone = 'scatter'


[style.default.timeseries-2panel]
clone = 'scatter'
legend_kws = {ncol = 2}

[style.main.timeseries-2panel]
clone = 'scatter'

[style.ref.timeseries-2panel]
clone = 'scatter'

[style.context.timeseries-2panel]
clone = 'scatter'


[style.default.delta-timeseries]
clone = 'timeseries'

[style.main.delta-timeseries]
clone = 'timeseries'

[style.ref.delta-timeseries]
clone = 'timeseries'

[style.context.delta-timeseries]
clone = 'timeseries'


[style.default.resampled-timeseries]
clone = 'scatter'
legend_kws = {ncol = 2}

[style.main.resampled-timeseries]
clone = 'scatter'

[style.ref.resampled-timeseries]
clone = 'scatter'

[style.context.resampled-timeseries]
clone = 'scatter'


[style.default.rolling-timeseries]
all = {marker = "o", markersize = 1, color="gray"}
flag0 = {marker = "o", markersize = 1, color="gray"}
flagged = {marker = "o", markersize = 1, color="red"}
median = {marker = "o", markersize = 1, color="black"}
mean = {marker = "o", markersize = 1, color="hotpink"}
std = {marker = "o", markersize = 1, color="green"}
quantile = {marker = "o", markersize = 1, color="green"}
legend_kws = {ncol = 2}

[style.main.rolling-timeseries]
all = {color = "royalblue"}
flag0 = {color = "royalblue"}

[style.ref.rolling-timeseries]
all = {color = "lightgray", zorder = 1.7}
flag0 = {color = "lightgray", zorder = 1.7}
median = {marker = "o", markersize = 1, color="slategray", zorder = 1.7}
mean = {marker = "o", markersize = 1, color="slategray", zorder = 1.7}
std = {marker = "o", markersize = 1, color="lightsteelblue", zorder = 1.7}
quantile = {marker = "o", markersize = 1, color="lightsteelblue", zorder = 1.7}

[style.context.rolling-timeseries]
all = {color = "deepskyblue"}
flag0 = {color = "deepskyblue"}


[style.default.rolling-derivative]
clone = "scatter"

[style.main.rolling-derivative]
clone = "scatter"

[style.ref.rolling-derivative]
clone = "scatter"

[style.context.rolling-derivative]
clone = "scatter"


[style.default.timing-error-am-pm]
both = {marker = "o", markersize = 1, linestyle="none"}
am = {color = "black"}
pm = {color = "gray"}

[style.main.timing-error-am-pm]
am = {color = "royalblue"}
pm = {color = "red"}


[style.default.timing-error-szas]
marker = "o"
markersize = 1
linestyle = "none"
color = ["tab:blue", "tab:orange", "tab:green", "tab:red", "tab:purple", "tab:brown", "tab:pink", "tab:gray", "tab:olive"]

[style.main.timing-error-szas]
color = ["royalblue", "red", "green"]


# ------------- #
# List of plots #
# ------------- #

[[plots]]
kind = "flag-analysis"

[[plots]]
kind = "timing-error-am-pm"
sza_range = [70, 80]

[[plots]]
kind = "timing-error-szas"
am_or_pm = "pm"
sza_ranges = [[70, 80], [40, 50], [20, 30]]

[[plots]]
kind = "rolling-timeseries"
yvar = "xluft"
ops = "median"

[[plots]]
kind = "rolling-derivative"
yvar = "zco2_4852a_zo"
dvar = "solzen"

[[plots]]
kind = "timeseries-2panel"
yvar = "xluft"
yerror_var = "xluft_error"

[[plots]]
kind = "timeseries-2panel"
yvar = "xco2"
yerror_var = "xco2_error"

[[plots]]
kind = "timeseries-2panel"
yvar = "xch4"
yerror_var = "xch4_error"

[[plots]]
kind = "timeseries-2panel"
yvar = "xco"
yerror_var = "xco_error"

[[plots]]
kind = "timeseries-2panel"
yvar = "xh2o"
yerror_var = "xh2o_error"

[[plots]]
kind = "timeseries-2panel"
yvar = "xhdo"
yerror_var = "xhdo_error"

[[plots]]
kind = "timeseries-2panel"
yvar = "xhf"
yerror_var = "xhf_error"

[[plots]]
kind = "timeseries-2panel"
yvar = "xn2o"
yerror_var = "xn2o_error"

[[plots]]
kind = "timeseries"
yvar = "vsf_co2"

[[plots]]
kind = "timeseries"
yvar = "vsf_lco2"

[[plots]]
kind = "timeseries"
yvar = "vsf_wco2"

[[plots]]
kind = "timeseries"
yvar = "vsf_hcl"

[[plots]]
kind = "timeseries"
yvar = "vsf_o2"

[[plots]]
kind = "timeseries"
yvar = "vsf_n2o"

[[plots]]
kind = "timeseries"
yvar = "vsf_hf"

[[plots]]
kind = "timeseries"
yvar = "vsf_h2o"

[[plots]]
kind = "timeseries"
yvar = "fvsi"

[[plots]]
kind = "timeseries"
yvar = "lse"

[[plots]]
kind = "timeseries"
yvar = "lsu"

[[plots]]
kind = "timeseries"
yvar = "solzen"

[[plots]]
kind = "timeseries"
yvar = "o2_7885_fs"

[[plots]]
kind = "timeseries"
yvar = "o2_7885_sg"

[[plots]]
kind = "timeseries"
yvar = "zco2_4852a_zo"

[[plots]]
kind = "timeseries"
yvar = "fco2_6154_cfampocl"

[[plots]]
kind = "timeseries"
yvar = "fco2_6154_cfperiod"

[[plots]]
kind = "timeseries"
yvar = "fco2_6154_cfphase"

[[plots]]
kind = "timeseries"
yvar = "dip"

[[plots]]
kind = "timeseries"
yvar = "mvd"

[[plots]]
kind = "timeseries"
yvar = "o2_7885_cl"

[[plots]]
kind = "timeseries"
yvar = "lco2_4852_cl"

[[plots]]
kind = "timeseries"
yvar = "hout"

[[plots]]
kind = "timeseries"
yvar = "tout"

[[plots]]
kind = "timeseries"
yvar = "tmod"

[[plots]]
kind = "delta-timeseries"
yvar1 = "tout"
yvar2 = "tmod"

[[plots]]
kind = "timeseries"
yvar = "h2o_dmf_out"

[[plots]]
kind = "timeseries"
yvar = "h2o_dmf_mod"

[[plots]]
kind = "delta-timeseries"
yvar1 = "h2o_dmf_out"
yvar2 = "h2o_dmf_mod"

[[plots]]
kind = "timeseries"
yvar = "pout"

[[plots]]
kind = "timeseries"
yvar = "pmod"

[[plots]]
kind = "delta-timeseries"
yvar1 = "pout"
yvar2 = "pmod"

[[plots]]
kind = "timeseries"
yvar = "wdir"

[[plots]]
kind = "timeseries"
yvar = "wspd"

[[plots]]
kind = "timeseries"
yvar = "prior_index"

[[plots]]
kind = "scatter"
xvar = "solzen"
yvar = "xco2"
match_axes_size = "xco2-vs-sza-hexbin"
legend_kws = {loc = "right", fontsize = 5, bbox_to_anchor = [1.55, 0.5]}

[[plots]]
kind = "hexbin"
key = "xco2-vs-sza-hexbin"
xvar = "solzen"
yvar = "xco2"
hexbin_flag_category = "all"
fit_flag_category = "flag0"

[[plots]]
kind = "scatter"
xvar = "solzen"
yvar = "xluft"
match_axes_size = "xluft-vs-sza-hexbin"
legend_kws = {loc = "right", fontsize = 5, bbox_to_anchor = [1.55, 0.5]}

[[plots]]
kind = "hexbin"
key = "xluft-vs-sza-hexbin"
xvar = "solzen"
yvar = "xluft"
hexbin_flag_category = "all"
fit_flag_category = "flag0"

[[plots]]
kind = "resampled-timeseries"
freq = "D"
op = "median"
yvar = "xluft"

[[plots]]
kind = "resampled-timeseries"
freq = "D"
op = "median"
yvar = "o2_7885_vsf_o2"

[[plots]]
kind = "resampled-timeseries"
freq = "W"
op = "median"
yvar = "xluft"

[[plots]]
kind = "resampled-timeseries"
freq = "W"
op = "median"
yvar = "o2_7885_vsf_o2"

